version: "3.6"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    restart: unless-stopped
    container_name: testimony.prod.web
    environment:
      APP_ENV: prod
    volumes:
      - ./testimony/:/testimony/
    ports:
      - "8000:8000"
    command: /bin/sh -c "sh scripts/entrypoint.sh gunicorn testimony.wsgi --bind 0.0.0.0:8000 -w 4 -t 660 --reload"
    networks:
      - postgres_net
      - redis_net

  db:
    image: postgres:12
    restart: unless-stopped
    container_name: testimony.prod.db
    ports:
      - 5545:5432
    environment:
      POSTGRES_USER: testimonyusr
      POSTGRES_PASSWORD: testimony123
      POSTGRES_DB: testimony-db
    networks:
      - postgres_net

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: prod
    command: /bin/sh -c "sh scripts/worker.sh"
    container_name: testimony.prod.celery
    volumes:
      - ./testimony/:/testimony/
    networks:
      - redis_net
      - postgres_net

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: prod
    command: /bin/sh -c "sh scripts/beat.sh"
    container_name: testimony.prod.beat
    volumes:
      - ./testimony/:/testimony/
    networks:
      - redis_net
      - postgres_net

  redis:
    image: redis:6
    container_name: testimony.prod.redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data
    networks:
      - redis_net

networks:
  postgres_net:
  redis_net:
